image: registry.novisci.com/nsstat/statocker/r/pkgdev:3.6.2

variables:
  RPKG: smd

stages:
  - testing
  - cran_check
  - package

testing:
  stage: testing
  script:
    - R -e 'devtools::check(manual = FALSE)'

cran_check:
# Per CRAN Repository Policy:
# I have checked the submission using R CMD check --as-cran and a current version
# of r-devel
  image: registry.novisci.com/nsstat/statocker/r/develcran
  stage: cran_check
  script:
    - R -e "install.packages(c('stddiff', 'tableone'))"
    - R CMD build .
    - "VERS=`grep 'Version:' DESCRIPTION | sed -e 's/Version: //'`"
    - R CMD check $RPKG_$VERS.tar.gz --as-cran

package:
  stage: package
  script:
    - rm -rf .git
    - R CMD build .

site:
  stage: package
  only:
     - master
  script:
     - R -e 'pkgdown::build_site()'
     - aws s3 sync $CI_PROJECT_DIR/docs/ s3://docs.novisci.com/$RPKG/ --delete --acl public-read

minicran:
  stage: package
  only:
    - master
  script:
    - Rscript -e "library(miniCRAN); addLocalPackage('${RPKG}', pkgPath='..', path='/mnt/cran.novisci.com', type='source', build=TRUE)"
    - Rscript -e "drat::archivePackages(repopath='/mnt/cran.novisci.com', pkg = '${RPKG}')"
