image: registry.novisci.com/infrastructure/r-build-dock:master

stages:
  - testing
  - package
#  - coverage

before_script:
  # Convert the incoming branch/tag reference to a DNS compliant name
  #   (eg. "ABCD-1234/branch.topic" becomes "ABCD-1234-branch_topic")
  - export SAFE_REF_NAME=$(echo $CI_COMMIT_REF_NAME | sed -e 's:/:-:g' -e 's:\.:_:g')
  - Rscript -e "print(getOption('repos'))"

testing:
  stage: testing
  script:
    - R -e 'install.packages(c("fastmatch", "miniCRAN", "MASS", "testthat", "stddiff", "tableone", "knitr", "covr"))'
# args = c("--no-vignettes", "--no-build-vignettes"),build_args = c("--no-build-vignettes", "--compact-vignettes=no"))'
    - R -e 'devtools::check(manual = FALSE)'

# Turning off coverage for now: getting smd() matches other packages failures
# and not sure why
#coverage:
#  stage: coverage
#  dependencies:
#    - testing
#  script:
#    - R -e 'covr::package_coverage(type = c("tests", "examples"))'


  #- Rscript -e "library(desc); d <- as.data.frame(desc_get_deps()); print(d); pkgs <- subset(d, type %in% c('Imports'), select = c('package'))[,1]; print(pkgs); install.packages(pkgs);"

# Store an artifact in gitlab that is the result of R CMD build
#   Keep it for a week by default. Any longer requires manual intervention
#   through the UI or API.
package:
  stage: package
  script:
    - R -e 'install.packages(c("fastmatch", "miniCRAN", "MASS", "testthat", "stddiff", "tableone", "knitr", "covr"))'
    - rm -rf .git
    - R CMD build .
  artifacts:
    name: "${CI_PROJECT_NAME}-${SAFE_REF_NAME}"
    paths:
      - ./${CI_PROJECT_NAME}_*
    expire_in: 1 week

minicran:
  stage: package
  only:
    - master
  script:
    - R -e 'install.packages(c("miniCRAN"))'
    - Rscript -e "library(miniCRAN); addLocalPackage('${CI_PROJECT_NAME}', pkgPath='..', path='/mnt/cran.novisci.com', type='source', build=TRUE)"

