image: rocker/tidyverse

stages:
  - testing
  - coverage

setup:
  stage: testing
  script:
    - R -e 'install.packages(c("fastmatch", "MASS", "testthat", "stddiff", "tableone", "knitr", "covr"))'

check:
  stage: testing
  dependencies:
    - setup
  script:
    - R -e 'devtools::check()'

coverage:
  stage: coverage
  dependencies:
    - check
  script:
    - R -e 'covr::package_coverage(type = c("tests", "examples"))'
