image: rocker/tidyverse

stages:
  - testing
  - coverage

testing:
  stage: testing
  script:
    - R -e 'install.packages(c("fastmatch", "MASS", "testthat", "stddiff", "tableone", "knitr", "covr"))'
    - R -e 'devtools::check(manual = FALSE, build_args = c("--no-build-vignettes", "--compact-vignettes=no"))'

coverage:
  stage: coverage
  dependencies:
    - testing
  script:
    - R -e 'covr::package_coverage(type = c("tests", "examples"))'
