image: rocker/tidyverse

stages:
  - testing
  - coverage

check:
  stage: testing
  script:
    - R -e 'install.packages(c("fastmatch", "MASS", "testthat", "stddiff", "tableone", "knitr", "covr"))'
    - R -e 'devtools::check()'
  tags:
    - r-packages

coverage:
  stage: coverage
  dependencies:
    - check
  script:
    - R -e 'covr::package_coverage(type = c("tests", "examples"))'
